addons: bridge: set the dummy port mac to be equal to bridge mac
In case of switchdev use-case when mlxsw driver offloads linux
bridge into Spectrum switch ASIC, it requires all router devices
to share the same MAC range, including bridge netdev and vlan
devices on top of it:

root@mellanox:~# ip addr add 2a02:6b8:fc21::1/57 dev vlan788
Error: mlxsw_spectrum: All router interface MAC addresses must \
have the same prefix.

Signed-off-by: Alexander Petrovskiy <alexpe@nvidia.com>